alias gpSetU='git push --set-upstream origin'
alias dcu='docker-compose up -d'
alias dcd='docker-compose down'
alias nv='nvim'
alias up="cd .."
alias startfeature="git flow feature start"
alias finishfeature="git flow feature finish"
alias ds="sudo service docker start"
alias python="python3"
